// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_JZn7Nfi2priSeo-VKJz0k7gWF8kXad0',
    appId: '1:1048129569498:web:df496c21b8204f4663dbe3',
    messagingSenderId: '1048129569498',
    projectId: 'trackerapp-4431b',
    authDomain: 'trackerapp-4431b.firebaseapp.com',
    storageBucket: 'trackerapp-4431b.firebasestorage.app',
    measurementId: 'G-JCKJP4XV5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDizE5QWHgLsh2cYi8NjO4rXdP88Cl-k_0',
    appId: '1:1048129569498:android:8dec08846318947963dbe3',
    messagingSenderId: '1048129569498',
    projectId: 'trackerapp-4431b',
    storageBucket: 'trackerapp-4431b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcICcu64jayhqjcpVDugy9pDqMExlJcU',
    appId: '1:1048129569498:ios:2b875865109221af63dbe3',
    messagingSenderId: '1048129569498',
    projectId: 'trackerapp-4431b',
    storageBucket: 'trackerapp-4431b.firebasestorage.app',
    androidClientId: '1048129569498-86bnrtf200bh9ao183vicq0spnsohghq.apps.googleusercontent.com',
    iosClientId: '1048129569498-nnvouctrhk89gh78p5kgqt0ns3hde99p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcICcu64jayhqjcpVDugy9pDqMExlJcU',
    appId: '1:1048129569498:ios:2b875865109221af63dbe3',
    messagingSenderId: '1048129569498',
    projectId: 'trackerapp-4431b',
    storageBucket: 'trackerapp-4431b.firebasestorage.app',
    androidClientId: '1048129569498-86bnrtf200bh9ao183vicq0spnsohghq.apps.googleusercontent.com',
    iosClientId: '1048129569498-nnvouctrhk89gh78p5kgqt0ns3hde99p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_JZn7Nfi2priSeo-VKJz0k7gWF8kXad0',
    appId: '1:1048129569498:web:8366075b0a5e147e63dbe3',
    messagingSenderId: '1048129569498',
    projectId: 'trackerapp-4431b',
    authDomain: 'trackerapp-4431b.firebaseapp.com',
    storageBucket: 'trackerapp-4431b.firebasestorage.app',
    measurementId: 'G-W20ZY4NJY2',
  );

}